### ISSUE TITLE
[feature request] list of goodfriends

### ISSUE THREAD

**Issue by TheMlgCat** [Blooym/GoodFriend#177]
it'd be nice if there was a list of your friends that also have goodfriend within the addon.

**Comment by Blooym** [comment]
With the way GoodFriend is currently designed it's not possible to implement this as I don't know who is using the addon since the server never gets that kinda data. 

The only way I can see something like this working is if I was to save the name of people who have sent notifications within the last 7-14 days and display that somewhere, which I'm not entirely sure is useful
